### ISSUE TITLE
Card Redesign

### ISSUE THREAD

**Issue by josephwegner** [josephwegner/carrick-issues-tracker#5]
Need to have more clarity and less complexity, especially as we add more features.

**Comment by josephwegner** [comment]
One potential design - note many of these are collapsible, and could default collapsed.

![carddesign1](https://user-images.githubusercontent.com/657707/95015474-bcb3a580-0612-11eb-8cc0-4cbb13d34e1f.PNG)

**Comment by CLBarajas** [comment]
This was my suggested concept, which combines the current three separate screens into three sections of a single view:

- **Linked Issues**: existing links between the conversation and any GitHub Issues
- **Link to Issue**: options for creating a new link between the conversation and a (new or existing) GitHub Issue, plus a way to quickly jump to the GitHub Issues list for a linked repository
- **Settings**: the initial configuration, and re-configuration, options

Some of these sections can be hidden when unused: without an already-linked issue, the top section isn't visible, and when you need to set up Carrick for the first time you'd only have the settings section.

I've played around with some other ways to consolidate info, as well: by combining status information along with the issue number, and merging the title/repo info, that would make the collapsed view easily glanced for an initial status:

![image](https://user-images.githubusercontent.com/2332192/95022100-159b3200-0643-11eb-8d89-5318643abee6.png)

It would also reduce the vertical space when looking for the issue title along with its history:

![image](https://user-images.githubusercontent.com/2332192/95022124-42e7e000-0643-11eb-8699-3087eac8df41.png)

The badge in the example above adds a `left-margin` of `6px` with a manual `style` attribute, because I don't think Help Scout's design expects to have any leading content for badges. If you did not make the issue info collapsible, I suppose you could `float: right` instead:

![image](https://user-images.githubusercontent.com/2332192/95023019-9872bb80-0648-11eb-9dfd-38511e18d87e.png)

I'm not familiar enough with the Help Scout sidebar app design language to be able to make this even more compact. For example, I figured it would be worth collapsing the history view until you need to view it, but it already sits in the linked issue's collapsible content so I don't know that you can double-up on it without having a headache.

**Comment by CLBarajas** [comment]
I had another thought, to make "Linked Issues" section more closely reflect the look in GitHub itself - I'll try to come up with another concept

**Comment by josephwegner** [comment]
This is what I've got so far, and am starting to like. A few issues I see, though:

- The "View on GitHub" button is visually expensive.
- The "View on GitHub" button is a bit confusing if it's related to the section above or the section below.
- The repo links for creating issues are a bit odd as a visual hierarchy - the icon is the same size and alignment as the section title's icon.

![carddesign2](https://user-images.githubusercontent.com/657707/95454810-8dfb3f00-0932-11eb-89dc-962e2013cdf4.PNG)

**Comment by CLBarajas** [comment]
I'm not sure I understand what the different icons next to the titles are supposed to represent. If it's status, GitHub Issues standardizes on a green exclamation point as open and red exclamation point with checkmark to represent closed.

Adding the issue number does make some more sense in the button to ensure it's identified properly. One other thing to consider is that you get the combination `btn btn-link` classes from Help Scout to create a link that takes the space of a button that looks more like a link, without some of the extra visual clutter of button borders.

**Comment by josephwegner** [comment]
Yeah - I was trying to use the Help Scout colors to see if it translated. It didn't work well. I'll try to get the GitHub icons directly in there. Will also check out `btn btn-link`.

**Comment by josephwegner** [comment]
Another attempt. Still not loving the View on GitHub link, but this may just be as good as it gets with Sidebar styling.

![image](https://user-images.githubusercontent.com/657707/96115361-6ebd5e00-0eac-11eb-861a-302d6618abec.png)

**Comment by CLBarajas** [comment]
That seems mostly fine? Without seeing the HTML it's hard to say what could be improved there, other than possibly adding a bit more vertical space between that and the timeline. (I'm also concerned about lengthy timelines taking up a ton of space - I bet at this point you could test against this repo to see how that looks.)

**Comment by josephwegner** [comment]
Shipped.
